// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package console

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func Wire() (Console, error) {
	consoleConsoleImpl := Provide()
	return consoleConsoleImpl, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	Provide, wire.Bind(new(Console), new(*consoleImpl)),
)
